form:
  title: CustomNamesForGeyserMC
  enterNick: Enter your nick
  example: ElPrimo
  wrongTitle: Error
  wrongNick: Please use normal nick

reconnect: Please reconnect to server again

useMetric: true

checkUpdates: true
version:
  new: pls download new plugin version https://github.com/Mirik9724/CustomNamesForGeyserMC/releases
  noFound: You use a latest version
  er: Wr cann`t check of updates